# secrets.GITHUB_TOKEN を使うには、リポジトリのSettingのActionsのGeneralからWorkflow Permissionを書き込み可能にしないといけない
name: ci
on:
  pull_request:
# concurrencyを設定してワークフローが複数同時実行されないように制御する
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  Rubocop:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
      # - run: bundle exec rubocop -C false # reviewdog使うのでコメントアウト
      - uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile
          reporter: github-pr-review
  RSpec:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
      - run: bundle exec rspec